# SEAL adaptation experiment configuration.
# Uses the base TinyGPT settings and specifies self-edit budgets that align
# with the orchestration prompt.

base_config: configs/base_config.yaml

seal:
  enabled: true
  candidates: 4
  max_edit_tokens: 128
  inner_steps: [1, 3, 10, 30]
  update_target: "lora"
  lora_rank: [4, 8]
  rest:
    topk: 1
    sft_epochs: 1
  reward: "delta_val_loss"
  eval_subset: 200
  logs: "results/seal_gpt2/adapt.jsonl"

policy:
  backend: "mlx"
  model_path: "$HOME/models/gpt2-mlx"

