# Configuration for context length scaling experiments
# Sweeps across different sequence lengths

model:
  vocab_size: 50257
  d_model: 128
  n_layers: 6
  n_heads: 8
  max_seq_len: 128  # Will be swept: [128, 256, 512]
  dropout: 0.1

data:
  dataset_name: "tinystories"
  tokenizer_type: "char"
  max_length: 128  # Will be swept to match max_seq_len
  stride: 64
  batch_size: 32
  num_workers: 4
  max_samples: 5000
  data_fraction: 0.05
  seed: 42

training:
  num_epochs: 2
  learning_rate: 3e-4
  weight_decay: 0.01
  warmup_steps: 50
  max_grad_norm: 1.0
  use_amp: true
  eval_interval: 100
  save_interval: 300
  log_interval: 25

experiment:
  name: "context_scaling"
  description: "Context length scaling experiment"
  tags: ["scaling", "context", "sequence_length"]

# Sweep parameters
sweep:
  parameter: "max_seq_len"
  values: [128, 256, 512]
  adjust_data_length: true  # Adjust data max_length to match