# Configuration for model depth scaling experiments
# Sweeps across different number of layers

model:
  vocab_size: 50257
  d_model: 128
  n_layers: 4  # Will be swept: [2, 4, 6, 8]
  n_heads: 8
  max_seq_len: 256
  dropout: 0.1

data:
  dataset_name: "tinystories"
  tokenizer_type: "char"
  max_length: 256
  stride: 128
  batch_size: 32
  num_workers: 4
  max_samples: 5000
  data_fraction: 0.05
  seed: 42

training:
  num_epochs: 2
  learning_rate: 3e-4
  weight_decay: 0.01
  warmup_steps: 50
  max_grad_norm: 1.0
  use_amp: true
  eval_interval: 100
  save_interval: 300
  log_interval: 25

experiment:
  name: "depth_scaling"
  description: "Model depth scaling experiment"
  tags: ["scaling", "depth", "n_layers"]

# Sweep parameters
sweep:
  parameter: "n_layers"
  values: [2, 4, 6, 8]