# Configuration for data scaling experiments
# Sweeps across different amounts of training data

model:
  vocab_size: 50257
  d_model: 128
  n_layers: 6
  n_heads: 8
  max_seq_len: 256
  dropout: 0.1

data:
  dataset_name: "tinystories"
  tokenizer_type: "char"
  max_length: 256
  stride: 128
  batch_size: 32
  num_workers: 4
  max_samples: null  # Will be determined by data_fraction
  data_fraction: 0.05  # Will be swept: [0.02, 0.05, 0.1, 0.2]
  seed: 42

training:
  num_epochs: 2
  learning_rate: 3e-4
  weight_decay: 0.01
  warmup_steps: 50
  max_grad_norm: 1.0
  use_amp: true
  eval_interval: 100
  save_interval: 300
  log_interval: 25

experiment:
  name: "data_scaling"
  description: "Training data scaling experiment"
  tags: ["scaling", "data", "data_fraction"]

# Sweep parameters
sweep:
  parameter: "data_fraction"
  values: [0.02, 0.05, 0.1, 0.2]